name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  ci:
    name: Run example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo 'Content here. You *can* use Markdown.' | tee /tmp/report.md
      - uses: ./
        with:
          name: Report name
          title: Report title here
          body-file: /tmp/report.md
